# Generated by Django 3.2.3 on 2021-05-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
