# Generated by Django 3.2.3 on 2021-06-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='home_page_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
