# Generated by Django 3.2.3 on 2021-06-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_home_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
