# Generated by Django 3.2.3 on 2021-06-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_image_priority'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('post', 'priority')},
        ),
    ]
